; Generated by tool/build.dart -- do not edit.
; Rewritten on every Windows build; describes the build that just ran.
#define MyProduct "gistx"
#define MyAppVersion "1.3.0+8"
#define MyAppVersionFile "1.3.0-build8"
