import java.util.Properties
import java.io.FileInputStream

// android/product.properties is generated by tool/build.dart from
// tool/product/android/<product>.properties immediately before each build
// (see CLAUDE.md's "two axes" section). Its committed content is always the
// GiSTX product, so this file works even if the tool was never run.
val productPropertiesFile = rootProject.file("product.properties")
val productProperties = Properties()
if (productPropertiesFile.exists()) {
    productProperties.load(FileInputStream(productPropertiesFile))
}

fun productProperty(key: String): String =
    productProperties.getProperty(key)
        ?: error("${productPropertiesFile.path} is missing required key \"$key\". " +
            "It should be generated from tool/product/android/<product>.properties.")

setProperty("archivesBaseName", productProperty("archivesBaseName"))

plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    // Internal only (the R-class/MainActivity package) -- not user-visible
    // identity, so this stays fixed across products. See CLAUDE.md.
    namespace = "com.gistx.gistx"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    sourceSets {
        getByName("main") {
            res.srcDirs("src/main/res", productProperty("iconResDir"))
        }
    }

    val keystorePropertiesFile = rootProject.file(productProperty("keystoreProperties"))
    val keystoreProperties = Properties()
    if (keystorePropertiesFile.exists()) {
        keystoreProperties.load(FileInputStream(keystorePropertiesFile))
    }

    fun keystoreProperty(key: String): String =
        keystoreProperties.getProperty(key)
            ?: error("${keystorePropertiesFile.path} is missing \"$key\" (or the file " +
                "itself is missing). See the README for how to create it.")

    signingConfigs {
        create("release") {
            keyAlias = keystoreProperty("keyAlias")
            keyPassword = keystoreProperty("keyPassword")
            storeFile = file(keystoreProperty("storeFile"))
            storePassword = keystoreProperty("storePassword")
        }
    }

    defaultConfig {
        applicationId = productProperty("applicationId")
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        manifestPlaceholders["appLabel"] = productProperty("appLabel")
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("release")
        }
    }
}

flutter {
    source = "../.."
}
